"""empty message

Revision ID: 06ecaa3ce8d6
Revises: e2c86ad35888
Create Date: 2021-04-27 23:38:16.756155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ecaa3ce8d6'
down_revision = 'e2c86ad35888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Empresa',
    sa.Column('EMPRESA_ID', sa.Integer(), nullable=False),
    sa.Column('EMPRESA_NOMBRE', sa.String(length=120), nullable=False),
    sa.Column('EMPRESA_UBICACION', sa.String(length=120), nullable=True),
    sa.Column('EMPRESA_TELEFONO', sa.String(length=10), nullable=True),
    sa.Column('EMPRESA_CELULAR', sa.String(length=10), nullable=True),
    sa.Column('EMPRESA_DESCRIPCION', sa.String(length=200), nullable=True),
    sa.Column('EMPRESA_LATITUD', sa.String(length=50), nullable=True),
    sa.Column('EMPRESA_LONGITUD', sa.String(length=50), nullable=True),
    sa.Column('EMPRESA_OTROS', sa.String(length=120), nullable=True),
    sa.Column('EMPRESA_FOTO_FONDO', sa.String(length=120), nullable=True),
    sa.Column('EMPRESA_LOGO', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('EMPRESA_ID'),
    sa.UniqueConstraint('EMPRESA_NOMBRE')
    )
    op.create_table('Usuarios',
    sa.Column('USUARIO_ID', sa.Integer(), nullable=False),
    sa.Column('USUARIO_EMAIL', sa.String(length=120), nullable=False),
    sa.Column('USUARIO_PASSWORD', sa.String(length=80), nullable=False),
    sa.Column('USUARIO_IS_ACTIVE', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('USUARIO_ID'),
    sa.UniqueConstraint('USUARIO_EMAIL')
    )
    op.create_table('Actividades',
    sa.Column('ACTIVIDAD_ID', sa.Integer(), nullable=False),
    sa.Column('ACTIVIDAD_NOMBRE', sa.String(length=120), nullable=False),
    sa.Column('ACTIVIDAD_ENTRENADOR', sa.String(length=120), nullable=True),
    sa.Column('ACTIVIDAD_LUGAR', sa.String(length=120), nullable=True),
    sa.Column('ACTIVIDAD_PRECIO', sa.Integer(), nullable=True),
    sa.Column('ACTIVIDAD_ESPACIOS', sa.Integer(), nullable=True),
    sa.Column('ACTIVIDAD_ESPACIOS_DISPONIBLES', sa.Integer(), nullable=True),
    sa.Column('ACTIVIDAD_DESCRIPCION', sa.String(length=200), nullable=True),
    sa.Column('ACTIVIDAD_ESTADO', sa.String(length=15), nullable=True),
    sa.Column('ACTIVIDAD_DIA_SEMANA', sa.String(length=10), nullable=True),
    sa.Column('ACTIVIDAD_FECHA_INICIO', sa.Date(), nullable=True),
    sa.Column('ACTIVIDAD_HORA_INICIO', sa.String(length=30), nullable=True),
    sa.Column('ACTIVIDAD_DURACION', sa.Integer(), nullable=True),
    sa.Column('ACTIVIDAD_FOTO', sa.String(length=120), nullable=True),
    sa.Column('EMPRESA_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EMPRESA_ID'], ['Empresa.EMPRESA_ID'], ),
    sa.PrimaryKeyConstraint('ACTIVIDAD_ID')
    )
    op.create_table('Anuncios',
    sa.Column('ANUNCIO_ID', sa.Integer(), nullable=False),
    sa.Column('ANUNCIO_NOMBRE', sa.String(length=120), nullable=False),
    sa.Column('ANUNCIO_DESCRIPCION', sa.String(length=200), nullable=True),
    sa.Column('ANUNCIO_FOTO_FONDO', sa.String(length=120), nullable=True),
    sa.Column('EMPRESA_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EMPRESA_ID'], ['Empresa.EMPRESA_ID'], ),
    sa.PrimaryKeyConstraint('ANUNCIO_ID')
    )
    op.create_table('Participantes',
    sa.Column('LISTA_ID', sa.Integer(), nullable=False),
    sa.Column('ACTIVIDAD_ID', sa.Integer(), nullable=True),
    sa.Column('PERSONA_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ACTIVIDAD_ID'], ['Actividades.ACTIVIDAD_ID'], ),
    sa.ForeignKeyConstraint(['PERSONA_ID'], ['Usuarios.USUARIO_ID'], ),
    sa.PrimaryKeyConstraint('LISTA_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Participantes')
    op.drop_table('Anuncios')
    op.drop_table('Actividades')
    op.drop_table('Usuarios')
    op.drop_table('Empresa')
    # ### end Alembic commands ###
