"""empty message

Revision ID: c53e1ea19982
Revises: 06ecaa3ce8d6
Create Date: 2021-05-16 20:00:47.641148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53e1ea19982'
down_revision = '06ecaa3ce8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('USUARIO_IS_ADMIN', sa.Boolean(), nullable=True))
    op.alter_column('Usuarios', 'USUARIO_IS_ACTIVE',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Usuarios', 'USUARIO_IS_ACTIVE',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('Usuarios', 'USUARIO_IS_ADMIN')
    # ### end Alembic commands ###
